version: 0.1.{build}
image: Visual Studio 2019

install:
  - choco install gitversion.portable --version 4.0.0 -y

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  verbosity: normal

after_build:
  - cmd: ECHO nuget pack Semantic.GlobalPayments.Hpp\Semantic.GlobalPayments.Hpp.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack Semantic.GlobalPayments.Hpp\Semantic.GlobalPayments.Hpp.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Semantic.GlobalPayments.Hpp.%GitVersion_NuGetVersion%.nupkg"